#!/usr/bin/env python
# CHEST motion
# 0: limit lower="-3.14159" upper="3.14159" effort="100" velocity="1.0"

from trajectory_msgs.msg import JointTrajectoryPoint, JointTrajectory
import numpy as np
import rospy
import time
import sys

class RightArm:

    def __init__(self, joint):
        self.pub = rospy.Publisher("/torso_controller/command", JointTrajectory, queue_size=1)
        self.names = [u'CHEST_JOINT0']
        self.rarm_limits = [(-3.1, 3.1)]
        self.joint_num = int(joint[1])

    def range_tester(self):
        initpos = np.zeros(1)
        lower = np.zeros(1)
        upper = np.zeros(1)
        lower[self.joint_num] = self.rarm_limits[self.joint_num][0]
        upper[self.joint_num] = self.rarm_limits[self.joint_num][1]

        pos = [lower, upper, initpos]
        timing = [5.0, 15.0, 20.0]
        trajectory_time = timing[len(timing)-1]

        trajectory_message = JointTrajectory()
        trajectory_message.joint_names = [x.encode('ascii') for x in self.names]
        for i in range(0, len(pos)):
            point = JointTrajectoryPoint()
            point.velocities = np.zeros(1).tolist()
            point.positions = pos[i].tolist()
            point.time_from_start = rospy.Duration(timing[i])
            trajectory_message.points.append(point)

        trajectory_message.header.stamp = rospy.Time.now()
        print("Moving through joint limit range of CHEST_JOINT" + str(self.joint_num))
        # print(trajectory_message)
        time.sleep(2)
        self.pub.publish(trajectory_message)


def main(args):
    rospy.init_node("right_arm_motion_tester")
    rarm = RightArm(args)
    rarm.range_tester()

if __name__ == '__main__':
    main(sys.argv)