#!/usr/bin/env python
# RARM_JOINT motion
# 0: limit lower="-1.570796" upper="1.570796" effort="150" velocity="1.0"
# 1: limit lower="-2.44346" upper="1.047197" effort="150" velocity="1.0"
# 2: limit lower="-1.22173" upper="1.570796" effort="150" velocity="1.0"
# 3: limit lower="-1.74532" upper="3.141592" effort="150" velocity="1.0"
# 4: limit lower="-3.5779" upper="1.134464" effort="150" velocity="1.0"
# 5: limit lower="-4.712388" upper="4.712388" effort="150" velocity="1.0"

from trajectory_msgs.msg import JointTrajectoryPoint, JointTrajectory
import numpy as np
import rospy
import time
import sys

class RightArm:

    def __init__(self, joint):
        self.pub = rospy.Publisher("/collision_larm_controller/command", JointTrajectory, queue_size=1)
        self.names = [u'LARM_JOINT0', u'LARM_JOINT1', u'LARM_JOINT2', u'LARM_JOINT3', u'LARM_JOINT4', u'LARM_JOINT5']
        self.larm_limits = [(-1.5, 1.5),
                            (-2.4, 0.9),
                            (-1.2, 1.),
                            (-1.7, 3.1),
                            (-3.5, 1.1),
                            (-4.7, 4.7)]
        self.joint_num = int(joint[1])

    def range_tester(self):
        initpos = np.zeros(6)
        lower = np.zeros(6)
        upper = np.zeros(6)
        lower[self.joint_num] = self.larm_limits[self.joint_num][0]
        upper[self.joint_num] = self.larm_limits[self.joint_num][1]

        pos = [lower, upper, initpos]
        timing = [3.0, 9.0, 12.0]
        trajectory_time = timing[len(timing)-1]

        trajectory_message = JointTrajectory()
        trajectory_message.joint_names = [x.encode('ascii') for x in self.names]
        for i in range(0, len(pos)):
            point = JointTrajectoryPoint()
            point.velocities = np.zeros(6).tolist()
            point.positions = pos[i].tolist()
            point.time_from_start = rospy.Duration(timing[i])
            trajectory_message.points.append(point)

        trajectory_message.header.stamp = rospy.Time.now()
        print("Moving through joint limit range of LARM_JOINT" + str(self.joint_num))
        # print(trajectory_message)
        time.sleep(2)
        self.pub.publish(trajectory_message)


def main(args):
    rospy.init_node("right_arm_motion_tester")
    rarm = RightArm(args)
    rarm.range_tester()

if __name__ == '__main__':
    main(sys.argv)