#!/usr/bin/env python
# Brings RARM into collision with LARM
# 0: limit lower="-1.570796" upper="1.570796" effort="150" velocity="1.0"
# 1: limit lower="-2.44346" upper="1.047197" effort="150" velocity="1.0"
# 2: limit lower="-1.22173" upper="1.570796" effort="150" velocity="1.0"
# 3: limit lower="-1.74532" upper="3.141592" effort="150" velocity="1.0"
# 4: limit lower="-3.5779" upper="1.134464" effort="150" velocity="1.0"
# 5: limit lower="-4.712388" upper="4.712388" effort="150" velocity="1.0"

from trajectory_msgs.msg import JointTrajectoryPoint, JointTrajectory
import numpy as np
import rospy
import time
import sys

class RightArm:

    def __init__(self, joint):
        self.pub = rospy.Publisher("/collision_rarm_controller/command", JointTrajectory, queue_size=1)
        self.names = [u'RARM_JOINT0', u'RARM_JOINT1', u'RARM_JOINT2', u'RARM_JOINT3', u'RARM_JOINT4', u'RARM_JOINT5']
        self.rarm_limits = [(-1.5, 1.5),
                            (-2.4, 0.9),
                            (-1.2, 1.),
                            (-1.7, 3.1),
                            (-3.5, 1.1),
                            (-4.7, 4.7)]

    def collide(self):
        desired = np.zeros(6)
        desired[0] = 1.5 #self.rarm_limits[0][1]

        pos = desired
        timing = 4.0

        trajectory_message = JointTrajectory()
        trajectory_message.joint_names = [x.encode('ascii') for x in self.names]
        point = JointTrajectoryPoint()
        point.velocities = np.zeros(6).tolist()
        point.positions = pos.tolist()
        point.time_from_start = rospy.Duration(timing)
        trajectory_message.points.append(point)

        trajectory_message.header.stamp = rospy.Time.now()
        print("Colliding")
        print(trajectory_message.points[0].positions)
        print(len(trajectory_message.points))
        time.sleep(2)
        self.pub.publish(trajectory_message)


def main(args):
    rospy.init_node("right_arm_motion_tester")
    rarm = RightArm(args)
    rarm.collide()

if __name__ == '__main__':
    main(sys.argv)